version: "3"

services:
  app:
    build:
      context: ./
    command: yarn start
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: 8080
    volumes:
      - ".:/usr/src/app"
  localtunnel:
    build:
      context: ./
    command: yarn lt --port 8080 -l app --subdomain slack-english-coach --print-requests
    volumes:
      - ".:/usr/src/app"
